build: tema1 tema1_par


tema1: tema1.c helpers.c
	gcc tema1.c helpers.c -o tema1 -lm -Wall -Wextra

tema1_par: tema1_par.c
	gcc tema1_par.c helpers.c -o tema1_par -lm -Wall -Wextra

clean:
	rm -rf tema1 tema1_par